# Generated by Django 4.2.8 on 2024-12-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0002_alter_songgenre_genre_alter_songgenre_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songgenres', to='tunaapi.artist'),
        ),
    ]
